---
# This playbook defines the whole application stack.

# Apply common configuration to all hosts.
- hosts: localhost
  roles:
    - common

# Configure the WordPress application nodes.
- hosts: localhost
  roles:
    - wordpress
